### PR TITLE
Add C++14 standard support to adjust electron11 version.

### PR DESCRIPTION
**Pull request by linhanyu**
Add C++14 standard support to adjust electron11 version.

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
cc @paul-marechal

**Comment by paul-marechal** [comment]
@linhanyu alternatively, would it be fine to uplift this fork to upstream's latest?

See upstream's `bindings.gyp` file as of writing: https://github.com/microsoft/node-pty/blob/3794fb111c51f2fa03ee6150468cc462db76699a/binding.gyp

**Comment by linhanyu** [comment]
Oh, that's OK.

**Comment by paul-marechal** [comment]
Is that branch working for you? https://github.com/theia-ide/node-pty/tree/%40theia/node-pty

**Comment by linhanyu** [comment]
> Is that branch working for you? https://github.com/theia-ide/node-pty/tree/%40theia/node-pty

It works. But after I package theia with electron13(do some hacking), It would stuck when I open Terminal, which load 'conpty.node' in windows. it work well if I change the code and load 'winpty.node'. Both problem happened in theia0.9.6-beta.6 version and this branch.

**Comment by paul-marechal** [comment]
This is no longer required to work in Theia.

**Pull request closed without merging**
