### PR TITLE
uplift: 0.9.0

### PR DESCRIPTION
**Pull request by paul-marechal**
Uplift our fork to microsoft's 0.9.0

### CODE REVIEW

**Comment by simark** [comment]
Out of curiosity, does this bring any particular fix you needed?

**Comment by paul-marechal** [comment]
@simark not specifically, just part of catching up with upstream rather than waiting too long.

**Comment by simark** [comment]
> @simark not specifically, just part of catching up with upstream rather than waiting too long.

Good idea!

**Comment by paul-marechal** [comment]
Just fixed some merge issues.

**Pull request merged**
